version: "3"

services:
  my_app:
    container_name: my_app
    entrypoint: sh run.sh
    tty: true
    stdin_open: true
    image: container_my_app:latest
    build:
      context: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://tom:tom123@service.postgres:5432/my_app_postgres
    volumes:
      - ./:/opt/app/my_app/
    external_links:
      - service.postgres
    ports:
      - "5000:5000"

  service.postgres:
    container_name: my_app_postgres
    image: postgres
    volumes:
      - postgre-data-test:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=tom
      - POSTGRES_PASSWORD=tom123
      - POSTGRES_DB=my_app_postgres

volumes:
  postgre-data-test: